module.exports = { 'Customer Acct': 
   { type: 'Text',
     namealt: 'Customer Acct',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Date of Birth':
   { type: 'Text',
     namealt: 'Date of Birth',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Designated Recipient':
   { type: 'Text',
     namealt: 'Designated Recipient',
     flags: '0',
     value: '',
     justification: 'Left' },
  'City  State  ZIP':
   { type: 'Text',
     namealt: 'City / State / ZIP',
     flags: '0',
     value: '',
     justification: 'Left' },
  Telephone:
   { type: 'Text',
     namealt: 'Telephone',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Fax Number':
   { type: 'Text',
     namealt: 'Fax Number',
     flags: '0',
     value: '',
     justification: 'Left' },
  Physician:
   { type: 'Button',
     namealt: 'Physician',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  Client:
   { type: 'Button',
     namealt: 'Client',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'Count and Motility':
   { type: 'Button',
     namealt: 'Count and Motility',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'Complete Semen Analysis':
   { type: 'Button',
     namealt: 'Complete Semen Analysis',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  Morphology:
   { type: 'Button',
     namealt: 'Morphology',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'Standard Wash':
   { type: 'Button',
     namealt: 'Standard Wash',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'Density Gradient Wash':
   { type: 'Button',
     namealt: 'Density Gradient Wash',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'Retrograde Ejaculation see attached report sheet for urine analysis':
   { type: 'Button',
     namealt: 'Retrograde Ejaculation (see attached report sheet for urine analysis',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  Masturbation:
   { type: 'Button',
     namealt: 'Masturbation',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  Onsite:
   { type: 'Button',
     namealt: 'Onsite',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'Days of abstinence':
   { type: 'Text',
     namealt: 'Days of abstinence',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Portion lost':
   { type: 'Text',
     namealt: 'Portion lost',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Time of analysis':
   { type: 'Text',
     namealt: 'Time of analysis',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Not Applicable':
   { type: 'Button',
     namealt: 'Not Applicable',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  Concentration:
   { type: 'Text',
     namealt: 'Concentration',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Normal Forms':
   { type: 'Text',
     namealt: 'Normal Forms',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Abnormal Forms':
   { type: 'Text',
     namealt: 'Abnormal Forms',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Total Sperm Count':
   { type: 'Text',
     namealt: 'Total Sperm Count',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Progressive Motility':
   { type: 'Text',
     namealt: 'Progressive Motility',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Head Defect':
   { type: 'Text',
     namealt: 'Head Defect',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Neck  Midpiece Defect':
   { type: 'Text',
     namealt: 'Neck / Midpiece Defect',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Tail Defect':
   { type: 'Text',
     namealt: 'Tail Defect',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Cytoplasmic Droplets':
   { type: 'Text',
     namealt: 'Cytoplasmic Droplets',
     flags: '0',
     value: '',
     justification: 'Left' },
  Agglutination:
   { type: 'Text',
     namealt: 'Agglutination',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Processing Tech':
   { type: 'Text',
     namealt: 'Processing Tech',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Faxed To':
   { type: 'Text',
     namealt: 'Faxed To',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Mailed To':
   { type: 'Text',
     namealt: 'Mailed To',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Reviewed By':
   { type: 'Text',
     namealt: 'Reviewed By',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Report Date':
   { type: 'Text',
     namealt: 'Report Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Did Client Produce a semen sample':
   { type: 'Button',
     flags: '49152',
     value: '',
     justification: 'Left',
     options: [ 'No', 'No_2', 'Off', 'Yes', 'Yes_2' ] },
  'Client Name':
   { type: 'Text',
     namealt: 'Client Name',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Physician Name':
   { type: 'Text',
     namealt: '[1]',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Street Address':
   { type: 'Text',
     namealt: '[2]',
     flags: '0',
     value: '',
     justification: 'Left' },
  'UA Client Name':
   { type: 'Text',
     namealt: 'Client Name',
     flags: '0',
     value: '',
     justification: 'Left' },
  'UA Customer Acct':
   { type: 'Text',
     namealt: 'Customer Acct',
     flags: '0',
     value: '',
     justification: 'Left' },
  other_results:
   { type: 'Text',
     namealt: 'undefined',
     flags: '0',
     value: '',
     justification: 'Left' },
  otherresults:
   { type: 'Button',
     namealt: 'Other',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  otherprocedure:
   { type: 'Button',
     namealt: 'Other',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  other_procedure:
   { type: 'Text',
     namealt: 'Other',
     flags: '0',
     value: '',
     justification: 'Left' },
  othercollection:
   { type: 'Button',
     namealt: 'Other',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  other_collection:
   { type: 'Text',
     namealt: 'Collection Location (check one',
     flags: '0',
     value: '',
     justification: 'Left' },
  offsite:
   { type: 'Button',
     namealt: 'Offsite /Time Rec‘d',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'time_rec\'d':
   { type: 'Text',
     namealt: 'undefined',
     flags: '0',
     value: '',
     justification: 'Left' },
  collection_date:
   { type: 'Text',
     namealt: 'Date / Time of collection',
     flags: '0',
     value: '',
     justification: 'Left' },
  'collection time':
   { type: 'Text',
     namealt: 'undefined',
     flags: '0',
     value: '',
     justification: 'Left' },
  volume:
   { type: 'Text',
     namealt: 'mL',
     flags: '0',
     value: '',
     justification: 'Left' },
  motility:
   { type: 'Text',
     namealt: 'undefined',
     flags: '0',
     value: '',
     justification: 'Left' },
  wbcs:
   { type: 'Text',
     namealt: 'M/mL',
     flags: '0',
     value: '',
     justification: 'Left' },
  'round cells':
   { type: 'Text',
     namealt: 'M/mL',
     flags: '0',
     value: '',
     justification: 'Left' },
  viscosity:
   { type: 'Text',
     namealt: '[1]',
     flags: '0',
     value: '',
     justification: 'Left' },
  pH:
   { type: 'Text',
     namealt: '[2]',
     flags: '0',
     value: '',
     justification: 'Left' },
  'ADDITIONAL COMMENTSRow1':
   { type: 'Text',
     namealt: 'ADDITIONAL COMMENTS:_Row_1',
     flags: '0',
     value: '',
     justification: 'Center' },
  'ADDITIONAL COMMENTSRow2':
   { type: 'Text',
     namealt: 'ADDITIONAL COMMENTS:_Row_2',
     flags: '0',
     value: '',
     justification: 'Center' },
  'ADDITIONAL COMMENTSRow3':
   { type: 'Text',
     namealt: 'ADDITIONAL COMMENTS:_Row_3',
     flags: '0',
     value: '',
     justification: 'Center' },
  'date faxed':
   { type: 'Text',
     namealt: 'Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  'date mailed':
   { type: 'Text',
     namealt: 'Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  'date reviewed':
   { type: 'Text',
     namealt: 'Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  'time of collection ua':
   { type: 'Text',
     namealt: 'undefined',
     flags: '0',
     value: '',
     justification: 'Left' },
  'date of collection ua':
   { type: 'Text',
     namealt: 'Date / Time of collection',
     flags: '0',
     value: '',
     justification: 'Left' },
  'time of analysis ua':
   { type: 'Text',
     namealt: 'Time of analysis',
     flags: '0',
     value: '',
     justification: 'Left' },
  'ua conc':
   { type: 'Text',
     namealt: 'Concentration',
     flags: '0',
     value: '',
     justification: 'Left' },
  'ua volume':
   { type: 'Text',
     namealt: 'mL',
     flags: '0',
     value: '',
     justification: 'Left' },
  'ua sperm count':
   { type: 'Text',
     namealt: 'Total Sperm Count',
     flags: '0',
     value: '',
     justification: 'Left' },
  'ua motility':
   { type: 'Text',
     namealt: 'undefined',
     flags: '0',
     value: '',
     justification: 'Left' },
  'ua progression':
   { type: 'Text',
     namealt: 'Progressive Motility',
     flags: '0',
     value: '',
     justification: 'Left' },
  'ua tech 1':
   { type: 'Text',
     namealt: 'Tech',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Not Applicable_2':
   { type: 'Button',
     namealt: 'Not Applicable',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'pf conc ua':
   { type: 'Text',
     namealt: 'Concentration',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pf volume ua':
   { type: 'Text',
     namealt: 'mL',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pf sperm count ua':
   { type: 'Text',
     namealt: 'Total Sperm Count',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pf motility ua':
   { type: 'Text',
     namealt: 'undefined',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pf progression ua':
   { type: 'Text',
     namealt: 'Progressive Motility',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pf tech ua':
   { type: 'Text',
     namealt: 'Tech',
     flags: '0',
     value: '',
     justification: 'Left' },
  'qc tech':
   { type: 'Text',
     namealt: 'Tech',
     flags: '0',
     value: '',
     justification: 'Left' },
  'qc date':
   { type: 'Text',
     namealt: 'Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pt n/a ua':
   { type: 'Button',
     namealt: 'Not Applicable',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'pt conc ua':
   { type: 'Text',
     namealt: 'Concentration',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pt volume ua':
   { type: 'Text',
     namealt: 'mL',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pt sperm count ua':
   { type: 'Text',
     namealt: 'Total Sperm Count',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pt motility ua':
   { type: 'Text',
     namealt: 'undefined',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pt progression ua':
   { type: 'Text',
     namealt: 'Progressive Motility',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pt tech ua':
   { type: 'Text',
     namealt: 'Tech',
     flags: '0',
     value: '',
     justification: 'Left' },
  'pt date ua':
   { type: 'Text',
     namealt: 'Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  '# of vials ua':
   { type: 'Text',
     namealt: 'Total Number of Vials',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Vials N/A ua':
   { type: 'Button',
     namealt: 'N/A',
     flags: '0',
     value: '',
     justification: 'Left',
     options: [ 'Off', 'On' ] },
  'UA DC 1':
   { type: 'Text',
     namealt: 'ADDITIONAL COMMENTS:_Row_1',
     flags: '0',
     value: '',
     justification: 'Center' },
  'Report Date_2':
   { type: 'Text',
     namealt: 'Report Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  Date_8:
   { type: 'Text',
     namealt: 'Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Reviewed By_2':
   { type: 'Text',
     namealt: 'Reviewed By',
     flags: '0',
     value: '',
     justification: 'Left' },
  Date_7:
   { type: 'Text',
     namealt: 'Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Mailed To_2':
   { type: 'Text',
     namealt: 'Mailed To',
     flags: '0',
     value: '',
     justification: 'Left' },
  Date_6:
   { type: 'Text',
     namealt: 'Date',
     flags: '0',
     value: '',
     justification: 'Left' },
  'Faxed To_2':
   { type: 'Text',
     namealt: 'Faxed To',
     flags: '0',
     value: '',
     justification: 'Left' },
  'ADDITIONAL COMMENTSRow5':
   { type: 'Text',
     namealt: 'ADDITIONAL COMMENTS:_Row_5',
     flags: '0',
     value: '',
     justification: 'Center' },
  'ADDITIONAL COMMENTSRow4': { type: 'Text', flags: '0', value: '', justification: 'Center' },
  'ADDITIONAL COMMENTSRow3_2':
   { type: 'Text',
     namealt: 'ADDITIONAL COMMENTS:_Row_3',
     flags: '0',
     value: '',
     justification: 'Center' },
  'ADDITIONAL COMMENTSRow2_2':
   { type: 'Text',
     namealt: 'ADDITIONAL COMMENTS:_Row_2',
     flags: '0',
     value: '',
     justification: 'Center' },
  'ADDITIONAL COMMENTSRow1_2':
   { type: 'Text',
     namealt: 'ADDITIONAL COMMENTS:_Row_1',
     flags: '0',
     value: '',
     justification: 'Center' },
  LG:
   { type: 'Text',
     flags: '0',
     value: 'LG',
     valuedefault: 'LG',
     justification: 'Left' },
  NY:
   { type: 'Text',
     flags: '0',
     value: 'NY',
     valuedefault: 'NY',
     justification: 'Left' },
  Clear:
   { type: 'Text',
     flags: '0',
     value: 'Clear',
     valuedefault: 'Clear',
     justification: 'Left' },
  'LG Address Field':
   { type: 'Text',
     flags: '4096',
     value: '11915 La Grange Ave',
     valuedefault: '11915 La Grange Ave',
     justification: 'Right' },
  'NY Address Field':
   { type: 'Text',
     flags: '4096',
     value: '369 Lexington Ave, Suite 401',
     valuedefault: '369 Lexington Ave, Suite 401',
     justification: 'Right' },
  'LG UA':
   { type: 'Text',
     flags: '0',
     value: 'LG',
     valuedefault: 'LG',
     justification: 'Left' },
  'NY UA':
   { type: 'Text',
     flags: '0',
     value: 'NY',
     valuedefault: 'NY',
     justification: 'Left' },
  'Clear UA':
   { type: 'Text',
     flags: '0',
     value: 'Clear',
     valuedefault: 'Clear',
     justification: 'Left' },
  'LG Address Field UA':
   { type: 'Text',
     flags: '4096',
     value: '11915 La Grange Ave',
     valuedefault: '11915 La Grange Ave',
     justification: 'Right' },
  'NY Address Field UA':
   { type: 'Text',
     flags: '4096',
     value: '369 Lexington Ave, Suite 401',
     valuedefault: '369 Lexington Ave, Suite 401',
     justification: 'Right' },
  'Address Select UA':
   { type: 'Button',
     flags: '49152',
     value: 'Clear UA',
     justification: 'Left',
     options: [ 'Clear UA', 'LG UA', 'NY UA', 'Off' ] },
  'Address Select':
   { type: 'Button',
     flags: '49152',
     value: 'Clear',
     justification: 'Left',
     options: [ 'Clear', 'LG', 'NY', 'Off' ] } }
